/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=PrivacyErasureBindings ./src/worker-configuration.d.ts` (hash: 5fce92b5e21e99d3c357e00f4eb8ab4e)
interface __BaseEnv_PrivacyErasureBindings {
	CINAAUTH_ERASURE_WEBHOOK_SECRET_STORE_V2: SecretsStoreSecret;
	CINAAUTH_ERASURE_CONFIG_KEK_STORE: SecretsStoreSecret;
	VERSION_METADATA: WorkerVersionMetadata;
	CINAAUTH_ERASURE_ALLOWED_HOSTS: "";
	ERASURE_COORDINATOR: DurableObjectNamespace<
		import("./index").ErasureCoordinator
	>;
	ERASURE_CONFIG: DurableObjectNamespace<
		import("./index").ErasureConfigDurableObject
	>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "ErasureCoordinator" | "ErasureConfigDurableObject";
	}
	interface Env extends __BaseEnv_PrivacyErasureBindings {}
}
interface PrivacyErasureBindings extends __BaseEnv_PrivacyErasureBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string
		? EnvType[Binding]
		: string;
};
declare namespace NodeJS {
	interface ProcessEnv
		extends StringifyValues<
			Pick<Cloudflare.Env, "CINAAUTH_ERASURE_ALLOWED_HOSTS">
		> {}
}
