/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=PrivacyErasureBindings ./src/worker-configuration.d.ts` (hash: 3dd1289965491c014dff22da37c4c2fa)
interface __BaseEnv_PrivacyErasureBindings {
	VERSION_METADATA: WorkerVersionMetadata;
	ERASURE_COORDINATOR: DurableObjectNamespace<
		import("./index").ErasureCoordinator
	>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "ErasureCoordinator";
	}
	interface Env extends __BaseEnv_PrivacyErasureBindings {}
}
interface PrivacyErasureBindings extends __BaseEnv_PrivacyErasureBindings {}
