/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=PrivacyErasureBindings ./src/worker-configuration.d.ts` (hash: 9f6aa17b31e2c33f6e48497c7928c8c2)
interface __BaseEnv_PrivacyErasureBindings {
	CINAAUTH_ERASURE_WEBHOOK_SECRET_STORE_V2: SecretsStoreSecret;
	VERSION_METADATA: WorkerVersionMetadata;
	ERASURE_COORDINATOR: DurableObjectNamespace<
		import("./index").ErasureCoordinator
	>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "ErasureCoordinator";
	}
	interface Env extends __BaseEnv_PrivacyErasureBindings {}
}
interface PrivacyErasureBindings extends __BaseEnv_PrivacyErasureBindings {}
