/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./src/worker-configuration.d.ts --env-interface DeliveryWorkerEnv --include-runtime false` (hash: 74fa568e5e9d13e4ee2ab16d2fac3157)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		CINAAUTH_DELIVERY_REPLAY_KV: KVNamespace;
		CINAAUTH_DELIVERY_WEBHOOK_SECRET_STORE_V2: SecretsStoreSecret;
		VERSION_METADATA: WorkerVersionMetadata;
		DELIVERY_ALLOWED_SKEW_SECONDS: "300";
		DELIVERY_REPLAY_TTL_SECONDS: "86400";
	}
}
interface DeliveryWorkerEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string
		? EnvType[Binding]
		: string;
};
declare namespace NodeJS {
	interface ProcessEnv
		extends StringifyValues<
			Pick<
				Cloudflare.Env,
				"DELIVERY_ALLOWED_SKEW_SECONDS" | "DELIVERY_REPLAY_TTL_SECONDS"
			>
		> {}
}
