/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./src/worker-configuration.d.ts --env-interface DeliveryWorkerEnv --include-runtime false` (hash: 5df003adc1ce55f7679bc8b5329c9c27)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "DeliveryProviderConfig";
	}
	interface Env {
		CINAAUTH_DELIVERY_REPLAY_KV: KVNamespace;
		CINAAUTH_DELIVERY_WEBHOOK_SECRET_STORE_V2: SecretsStoreSecret;
		CINAAUTH_DELIVERY_CONFIG_KEK_STORE: SecretsStoreSecret;
		VERSION_METADATA: WorkerVersionMetadata;
		DELIVERY_ALLOWED_SKEW_SECONDS: "300";
		DELIVERY_REPLAY_TTL_SECONDS: "86400";
		DELIVERY_CONFIG: DurableObjectNamespace<
			import("./index").DeliveryProviderConfig
		>;
	}
}
interface DeliveryWorkerEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string
		? EnvType[Binding]
		: string;
};
declare namespace NodeJS {
	interface ProcessEnv
		extends StringifyValues<
			Pick<
				Cloudflare.Env,
				"DELIVERY_ALLOWED_SKEW_SECONDS" | "DELIVERY_REPLAY_TTL_SECONDS"
			>
		> {}
}
