import type { DeliveryMessage } from "./delivery";

export interface CloudflareBindings extends Cloudflare.Env {
	/** Auth secret for signed sessions and tokens. */
	CINAAUTH_SECRET: string;
	/** Queue generated by wrangler typegen, narrowed to delivery messages here. */
	CINAAUTH_DELIVERY_QUEUE: Queue<DeliveryMessage>;
	/** Worker version metadata for readiness responses and structured logs. */
	VERSION_METADATA: WorkerVersionMetadata;
	/** Service token for cinaadmin console (auditLog writeTokens). */
	CINAUTH_ADMIN_SERVICE_KEY?: string;
	/** Required token that protects /api/migrate and /api/ready in production. */
	CINAAUTH_MIGRATION_TOKEN?: string;
	/** Optional HMAC secret for OAuth pairwise subject identifiers. */
	OAUTH_PAIRWISE_SECRET?: string;
	/** JSON array of cinaauth generic OAuth provider configs. */
	GENERIC_OAUTH_CONFIG?: string;
	/** Google client ID for the One Tap plugin. */
	GOOGLE_CLIENT_ID?: string;
	/** Cloudflare Turnstile secret for the captcha plugin. */
	CLOUDFLARE_TURNSTILE_SECRET_KEY?: string;
	CINAAUTH_DELIVERY_WEBHOOK_URL?: string;
	CINAAUTH_DELIVERY_WEBHOOK_SECRET?: string;
	/** Stripe settings; enable Stripe only when both secret and webhook secret exist. */
	STRIPE_SECRET_KEY?: string;
	STRIPE_WEBHOOK_SECRET?: string;
	STRIPE_DEFAULT_PRICE_ID?: string;
	STRIPE_DEFAULT_PLAN_NAME?: string;
}
