/* eslint-disable */
// Generated by Wrangler by running `wrangler types .\src\worker-configuration.d.ts --env-interface CloudflareBindings --include-runtime false` (hash: d8e7f1bb8335edd98edfa705fd409211)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		DB: D1Database;
		CINAAUTH_DELIVERY_QUEUE: Queue;
		VERSION_METADATA: WorkerVersionMetadata;
		CINAAUTH_URL: "https://auth.cinagroup.com";
	}
}
interface CloudflareBindings extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CINAAUTH_URL">> {}
}
