/* eslint-disable */
// Generated by Wrangler by running `wrangler types .\src\worker-configuration.d.ts --env-interface DeliveryWorkerEnv --include-runtime false` (hash: 7d81a3d21cec6f05977258c383f43398)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		CINAAUTH_DELIVERY_REPLAY_KV: KVNamespace;
		VERSION_METADATA: WorkerVersionMetadata;
		DELIVERY_ALLOWED_SKEW_SECONDS: "300";
		DELIVERY_REPLAY_TTL_SECONDS: "86400";
	}
}
interface DeliveryWorkerEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DELIVERY_ALLOWED_SKEW_SECONDS" | "DELIVERY_REPLAY_TTL_SECONDS">> {}
}
