apiVersion: v1
kind: Service
metadata:
  name: cinaauth
  namespace: cinaauth
  labels:
    app.kubernetes.io/name: cinaauth
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cinaauth
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
