/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv ./worker-configuration.d.ts` (hash: df54f91eee54fcf5d0cfd31b313269b8)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	CINAAUTH_URL: "https://auth.cinaseek.ai";
	CINAAUTH_REQUIRE_AUTH_WORKER_BINDING: "true";
	NEXT_PUBLIC_CINAAUTH_API_URL: "https://accounts.cinaseek.ai";
	AUTH_WORKER: Fetcher /* cinaauth-api */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string
		? EnvType[Binding]
		: string;
};
declare namespace NodeJS {
	interface ProcessEnv
		extends StringifyValues<
			Pick<
				Cloudflare.Env,
				| "CINAAUTH_URL"
				| "CINAAUTH_REQUIRE_AUTH_WORKER_BINDING"
				| "NEXT_PUBLIC_CINAAUTH_API_URL"
			>
		> {}
}
