# cinaauth Installation Script for Windows
# Usage: iwr -useb https://raw.githubusercontent.com/cinagroup/cinaauth/main/scripts/install.ps1 | iex

$ErrorActionPreference = 'Stop'

# Configuration
$REPO = 'cinagroup/cinaauth'
$BINARY_NAME = 'authframework'
$INSTALL_DIR = "${env:ProgramFiles}\cinaauth"
$CONFIG_DIR = "${env:USERPROFILE}\.config\authframework"
$TEMP_DIR = "${env:TEMP}\authframework-install"

# Create temp directory
if (Test-Path $TEMP_DIR) {
    Remove-Item -Path $TEMP_DIR -Recurse -Force
}
New-Item -ItemType Directory -Path $TEMP_DIR | Out-Null

# Helper Functions
function Write-ColorOutput {
    param(
        [string]$Message,
        [string]$Color = 'White',
        [string]$Prefix = ''
    )
    
    if ($Prefix) {
        Write-Host "$Prefix " -NoNewline -ForegroundColor $Color
    }
    Write-Host $Message
}

function Write-Info {
    param([string]$Message)
    Write-ColorOutput -Message $Message -Color Cyan -Prefix 'ℹ'
}

function Write-Success {
    param([string]$Message)
    Write-ColorOutput -Message $Message -Color Green -Prefix '✓'
}

function Write-Error {
    param([string]$Message)
    Write-ColorOutput -Message $Message -Color Red -Prefix '✗'
}

function Write-Warning {
    param([string]$Message)
    Write-ColorOutput -Message $Message -Color Yellow -Prefix '⚠'
}

function Get-LatestVersion {
    try {
        Write-Info 'Fetching latest version...'
        $response = Invoke-RestMethod -Uri "https://api.github.com/repos/$REPO/releases/latest"
        $version = $response.tag_name
        
        if ([string]::IsNullOrEmpty($version)) {
            throw 'Failed to get latest version'
        }
        
        Write-Success "Latest version: $version"
        return $version
    }
    catch {
        Write-Error "Failed to fetch latest version: $_"
        exit 1
    }
}

function Get-Architecture {
    $arch = $env:PROCESSOR_ARCHITECTURE
    
    switch ($arch) {
        'AMD64' { return 'x86_64' }
        'ARM64' { return 'aarch64' }
        default {
            Write-Error "Unsupported architecture: $arch"
            exit 1
        }
    }
}

function Download-And-Install {
    param(
        [string]$Version,
        [string]$Arch
    )
    
    $TARGET = "${Arch}-pc-windows-msvc"
    $ARCHIVE_NAME = "${BINARY_NAME}-${Version}-${TARGET}.zip"
    $DOWNLOAD_URL = "https://github.com/${REPO}/releases/download/${Version}/${ARCHIVE_NAME}"
    
    Write-Info "Downloading cinaauth ${Version} for ${TARGET}..."
    
    try {
        $archivePath = Join-Path $TEMP_DIR $ARCHIVE_NAME
        Invoke-WebRequest -Uri $DOWNLOAD_URL -OutFile $archivePath -UseBasicParsing
        
        Write-Info 'Extracting archive...'
        Expand-Archive -Path $archivePath -DestinationPath $TEMP_DIR -Force
        
        Write-Info "Installing binaries to ${INSTALL_DIR}..."
        
        # Create install directory
        if (-not (Test-Path $INSTALL_DIR)) {
            New-Item -ItemType Directory -Path $INSTALL_DIR -Force | Out-Null
        }
        
        # Copy binaries
        $binaries = @('authframework-server.exe', 'authframework-cli.exe')
        foreach ($binary in $binaries) {
            $sourcePath = Join-Path $TEMP_DIR $binary
            if (Test-Path $sourcePath) {
                Copy-Item -Path $sourcePath -Destination $INSTALL_DIR -Force
                Write-Success "Installed $binary"
            }
        }
        
        # Add to PATH if not already present
        $currentPath = [Environment]::GetEnvironmentVariable('Path', 'Machine')
        if ($currentPath -notlike "*$INSTALL_DIR*") {
            Write-Info "Adding ${INSTALL_DIR} to system PATH..."
            [Environment]::SetEnvironmentVariable(
                'Path',
                "$currentPath;$INSTALL_DIR",
                'Machine'
            )
            Write-Success 'Added to PATH (restart terminal to use)'
        }
        
        Write-Success 'cinaauth installed successfully!'
    }
    catch {
        Write-Error "Installation failed: $_"
        exit 1
    }
}

function Create-SampleConfig {
    Write-Info 'Creating sample configuration...'
    
    if (-not (Test-Path $CONFIG_DIR)) {
        New-Item -ItemType Directory -Path $CONFIG_DIR -Force | Out-Null
    }
    
    $configPath = Join-Path $CONFIG_DIR 'config.toml'
    
    $configContent = @"
# cinaauth Configuration File
# Generated by install script

[server]
host = "127.0.0.1"
port = 8080
workers = 4

[storage]
# Options: "memory", "sqlite", "postgres", "redis"
backend = "sqlite"
connection_string = "${env:LOCALAPPDATA}\authframework\data.db"

[security]
# Generate a secure secret key:
# openssl rand -base64 32
secret_key = "CHANGE_THIS_TO_A_SECURE_RANDOM_KEY"

[jwt]
issuer = "authframework"
access_token_ttl = 3600      # 1 hour
refresh_token_ttl = 2592000  # 30 days

[rate_limiting]
enabled = true
requests_per_second = 100
burst_size = 200

[cors]
enabled = true
allowed_origins = ["http://localhost:3000", "http://localhost:8080"]

[logging]
level = "info"
format = "json"

# OAuth 2.0 Configuration
[oauth]
enable_pkce = true
authorization_code_ttl = 600  # 10 minutes

# WebAuthn Configuration
[webauthn]
rp_name = "cinaauth"
rp_id = "localhost"
rp_origin = "http://localhost:8080"

# SAML Configuration
[saml]
entity_id = "http://localhost:8080/saml"
acs_url = "http://localhost:8080/api/v1/saml/acs"
"@
    
    Set-Content -Path $configPath -Value $configContent
    
    Write-Success "Sample configuration created at ${configPath}"
    Write-Warning 'Remember to update the secret_key and other settings before running in production!'
}

function Install-WindowsService {
    $response = Read-Host 'Install as Windows Service? (y/N)'
    if ($response -ne 'y' -and $response -ne 'Y') {
        return
    }
    
    Write-Info 'Installing Windows Service...'
    
    $serviceName = 'cinaauth'
    $displayName = 'cinaauth Authentication Server'
    $description = 'cinaauth - High-performance authentication and authorization server'
    $binaryPath = Join-Path $INSTALL_DIR 'authframework-server.exe'
    $configPath = Join-Path $CONFIG_DIR 'config.toml'
    
    # Stop service if it exists
    $existingService = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
    if ($existingService) {
        Write-Info 'Stopping existing service...'
        Stop-Service -Name $serviceName -Force
        sc.exe delete $serviceName | Out-Null
        Start-Sleep -Seconds 2
    }
    
    # Create service
    try {
        New-Service -Name $serviceName `
            -BinaryPathName "`"$binaryPath`" --config `"$configPath`"" `
            -DisplayName $displayName `
            -Description $description `
            -StartupType Manual
        
        Write-Success 'Windows Service installed successfully!'
        Write-Info "To start: Start-Service -Name $serviceName"
        Write-Info "To enable auto-start: Set-Service -Name $serviceName -StartupType Automatic"
    }
    catch {
        Write-Error "Failed to create service: $_"
    }
}

function Create-FirewallRule {
    $response = Read-Host 'Create Windows Firewall rule? (y/N)'
    if ($response -ne 'y' -and $response -ne 'Y') {
        return
    }
    
    Write-Info 'Creating Windows Firewall rule...'
    
    $ruleName = 'cinaauth Server'
    $binaryPath = Join-Path $INSTALL_DIR 'authframework-server.exe'
    
    # Remove existing rule if present
    $existingRule = Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue
    if ($existingRule) {
        Remove-NetFirewallRule -DisplayName $ruleName
    }
    
    try {
        New-NetFirewallRule -DisplayName $ruleName `
            -Direction Inbound `
            -Program $binaryPath `
            -Action Allow `
            -Profile Any `
            -Description 'Allow cinaauth Server traffic'
        
        Write-Success 'Firewall rule created successfully!'
    }
    catch {
        Write-Error "Failed to create firewall rule: $_"
        Write-Info 'You may need to run this script as Administrator'
    }
}

function Show-UsageInstructions {
    Write-Host ''
    Write-Host '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━' -ForegroundColor Green
    Write-Host '  cinaauth Installation Complete!' -ForegroundColor Green
    Write-Host '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━' -ForegroundColor Green
    Write-Host ''
    Write-Host 'Quick Start:' -ForegroundColor Cyan
    Write-Host '  1. Edit configuration:'
    Write-Host "     PS> notepad $CONFIG_DIR\config.toml"
    Write-Host ''
    Write-Host '  2. Generate a secure secret key:'
    Write-Host '     PS> [Convert]::ToBase64String((1..32 | ForEach-Object { Get-Random -Maximum 256 }))'
    Write-Host ''
    Write-Host '  3. Start the server:'
    Write-Host '     PS> authframework-server'
    Write-Host ''
    Write-Host '  4. Or use the CLI:'
    Write-Host '     PS> authframework-cli --help'
    Write-Host ''
    Write-Host 'Windows Service:' -ForegroundColor Cyan
    Write-Host '  PS> Start-Service -Name cinaauth'
    Write-Host '  PS> Set-Service -Name cinaauth -StartupType Automatic'
    Write-Host ''
    Write-Host 'Documentation:' -ForegroundColor Cyan
    Write-Host "  https://github.com/$REPO/blob/main/README.md"
    Write-Host ''
    Write-Host 'API Documentation:' -ForegroundColor Cyan
    Write-Host '  http://localhost:8080/api/docs (when server is running)'
    Write-Host ''
    Write-Host '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━' -ForegroundColor Green
    Write-Host ''
    Write-Warning "Note: Restart your terminal to use the 'authframework-*' commands"
}

# Main installation flow
function Main {
    Write-Host ''
    Write-Host '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━' -ForegroundColor Cyan
    Write-Host '  cinaauth Installer for Windows' -ForegroundColor Cyan
    Write-Host '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━' -ForegroundColor Cyan
    Write-Host ''
    
    # Check if running as administrator
    $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    if (-not $isAdmin) {
        Write-Warning 'Not running as Administrator - some features may be unavailable'
        Write-Info 'For full functionality, run: Start-Process powershell -Verb RunAs'
        Write-Host ''
    }
    
    # Detect architecture
    Write-Info 'Detecting architecture...'
    $arch = Get-Architecture
    Write-Success "Detected architecture: $arch"
    
    # Get latest version
    $version = Get-LatestVersion
    
    # Download and install
    Download-And-Install -Version $version -Arch $arch
    
    # Create configuration
    Create-SampleConfig
    
    # Install Windows Service (if admin)
    if ($isAdmin) {
        Install-WindowsService
        Create-FirewallRule
    }
    else {
        Write-Warning 'Skipping Windows Service and Firewall setup (requires Administrator)'
    }
    
    # Cleanup
    Write-Info 'Cleaning up temporary files...'
    Remove-Item -Path $TEMP_DIR -Recurse -Force -ErrorAction SilentlyContinue
    
    # Show usage instructions
    Show-UsageInstructions
}

# Run main function
try {
    Main
}
catch {
    Write-Error "Installation failed: $_"
    exit 1
}
