/// <reference types="@cloudflare/workers-types" />

// @ts-expect-error Generated by the OpenNext build before Wrangler bundles this entry.
import handler from "./.open-next/worker.js";

const esbuildNameHelper =
	'globalThis.__name ||= ((target, value) => Object.defineProperty(target, "name", { value, configurable: true }));';

const htmlRewriter = new HTMLRewriter().on("head", {
	element(element) {
		element.prepend(`<script>${esbuildNameHelper}</script>`, { html: true });
	},
});

export default {
	async fetch(request, env, ctx) {
		const response = await handler.fetch(request, env, ctx);
		if (!response.headers.get("content-type")?.includes("text/html")) {
			return response;
		}

		return htmlRewriter.transform(response);
	},
} satisfies ExportedHandler<CloudflareEnv>;

// @ts-expect-error Generated by the OpenNext build before Wrangler bundles this entry.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
