import type { DeliveryMessage } from "./delivery";
import type { PrivacyExportMessage } from "./privacy-export";

export interface CloudflareBindings extends Cloudflare.Env {
	/** Canonical cinatoken application origin registered as an OAuth audience. */
	CINAAUTH_CINATOKEN_ORIGIN?: string;
	/** Fixed cinatoken OAuth client identifier. */
	CINAAUTH_CINATOKEN_CLIENT_ID?: string;
	/** Auth secret for signed sessions and tokens. */
	CINAAUTH_SECRET: string;
	/** Raw secret used only to reconcile the fixed confidential Admin OIDC client. */
	CINAADMIN_OIDC_CLIENT_SECRET?: string;
	/** Private shared secret protecting the Admin Service Binding session bridge. */
	CINAADMIN_OIDC_BRIDGE_SECRET?: string;
	/** Raw secret used only to reconcile the fixed confidential cinatoken OIDC client. */
	CINATOKEN_OIDC_CLIENT_SECRET?: string;
	/** Private shared secret protecting the cinatoken Service Binding role bridge. */
	CINATOKEN_OIDC_BRIDGE_SECRET?: string;
	/** Read-only rollback source retained after the PostgreSQL cutover. */
	LEGACY_D1: D1Database;
	/** Queue generated by wrangler typegen, narrowed to delivery messages here. */
	CINAAUTH_DELIVERY_QUEUE: Queue<DeliveryMessage>;
	/** Private management and execution binding for the Privacy Erasure Worker. */
	CINAAUTH_ERASURE_SERVICE: Fetcher;
	/** Dedicated queue for asynchronous encrypted privacy exports. */
	CINAAUTH_PRIVACY_EXPORT_QUEUE: Queue<PrivacyExportMessage>;
	/** Private R2 bucket containing SSE-C encrypted export manifests and data. */
	CINAAUTH_PRIVACY_EXPORTS: R2Bucket;
	/** Customer-managed root key used to derive per-object SSE-C keys. */
	CINAAUTH_PRIVACY_EXPORT_KEY?: string;
	/** HTTPS endpoint that orchestrates deletion across external processors. */
	CINAAUTH_ERASURE_WEBHOOK_URL?: string;
	/** HMAC secret shared with the external erasure orchestrator. */
	CINAAUTH_ERASURE_WEBHOOK_SECRET?: string;
	/** Worker version metadata for readiness responses and structured logs. */
	VERSION_METADATA: WorkerVersionMetadata;
	/** Service token for cinaadmin console (auditLog writeTokens). */
	CINAUTH_ADMIN_SERVICE_KEY?: string;
	/** Required token that protects /api/migrate and /api/ready in production. */
	CINAAUTH_MIGRATION_TOKEN?: string;
	/** One-time cutover token; remove it immediately after D1 migration. */
	CINAAUTH_D1_MIGRATION_TOKEN?: string;
	/** Fail-closed database cutover state. */
	CINAAUTH_CUTOVER_STATE?: "maintenance" | "live";
	/** Explicit SIWE kill switch. Only the exact string "true" enables it. */
	CINAAUTH_SIWE_ENABLED?: string;
	/** Comma-separated EIP-155 chain IDs accepted by the SIWE verifier. */
	CINAAUTH_SIWE_ALLOWED_CHAIN_IDS?: string;
	/** EIP-4361 relying-party domain shown by the signing wallet. */
	CINAAUTH_SIWE_RP_DOMAIN?: string;
	/** Canonical HTTPS relying-party URI bound into every SIWE message. */
	CINAAUTH_SIWE_RP_URI?: string;
	/** Phase-one safety gate; production accepts only the exact value "false". */
	CINAAUTH_SIWE_ALLOW_LEGACY?: string;
	/** Phase-one safety gate; unknown wallets must not create users. */
	CINAAUTH_SIWE_AUTO_SIGNUP?: string;
	/** Optional HMAC secret for OAuth pairwise subject identifiers. */
	OAUTH_PAIRWISE_SECRET?: string;
	/** JSON array of cinaauth generic OAuth provider configs. */
	GENERIC_OAUTH_CONFIG?: string;
	/** Google client ID shared by One Tap and Google social sign-in. */
	GOOGLE_CLIENT_ID?: string;
	/** Google OAuth client secret; paired with GOOGLE_CLIENT_ID for social sign-in. */
	GOOGLE_CLIENT_SECRET?: string;
	/** GitHub OAuth App client ID. */
	GITHUB_CLIENT_ID?: string;
	/** GitHub OAuth App client secret. */
	GITHUB_CLIENT_SECRET?: string;
	/** Cloudflare Turnstile secret for the captcha plugin. */
	CLOUDFLARE_TURNSTILE_SECRET_KEY?: string;
	/** Public Cloudflare Turnstile widget key; paired with the secret key. */
	CLOUDFLARE_TURNSTILE_SITE_KEY?: string;
	CINAAUTH_DELIVERY_WEBHOOK_URL?: string;
	CINAAUTH_DELIVERY_WEBHOOK_SECRET?: string;
	/** Stripe settings; enable Stripe only when both secret and webhook secret exist. */
	STRIPE_SECRET_KEY?: string;
	STRIPE_WEBHOOK_SECRET?: string;
	STRIPE_DEFAULT_PRICE_ID?: string;
	STRIPE_DEFAULT_PLAN_NAME?: string;
	/** Versioned, fail-closed plan-to-feature and limit policy. */
	CINAAUTH_ENTITLEMENT_CONFIG?: string;
}
