/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings ./src/worker-configuration.d.ts` (hash: 29c218117912bb8298ad8ef2400654dc)
interface __BaseEnv_CloudflareBindings {
	CINAAUTH_PRIVACY_EXPORTS: R2Bucket;
	LEGACY_D1: D1Database;
	HYPERDRIVE: Hyperdrive;
	CINAAUTH_DELIVERY_QUEUE: Queue;
	CINAAUTH_PRIVACY_EXPORT_QUEUE: Queue;
	CINAAUTH_DELIVERY_WEBHOOK_SECRET_STORE_V2: SecretsStoreSecret;
	CINAAUTH_ERASURE_WEBHOOK_SECRET_STORE_V2: SecretsStoreSecret;
	CINAADMIN_OIDC_CLIENT_SECRET_STORE_V2: SecretsStoreSecret;
	CINAADMIN_OIDC_BRIDGE_SECRET_STORE_V2: SecretsStoreSecret;
	VERSION_METADATA: WorkerVersionMetadata;
	CINAAUTH_URL: "https://auth.cinaseek.ai";
	CINAAUTH_CUTOVER_STATE: "live";
	CINAAUTH_SIWE_ENABLED: "false";
	CINAAUTH_SIWE_ALLOWED_CHAIN_IDS: "1";
	CINAAUTH_SIWE_RP_DOMAIN: "accounts.cinaseek.ai";
	CINAAUTH_SIWE_RP_URI: "https://accounts.cinaseek.ai";
	CINAAUTH_SIWE_ALLOW_LEGACY: "false";
	CINAAUTH_SIWE_AUTO_SIGNUP: "false";
	RATE_LIMITER: DurableObjectNamespace<
		import("./index").RateLimitDurableObject
	>;
	CINAAUTH_DELIVERY_SERVICE: Fetcher /* cinaauth-delivery */;
	CINAAUTH_ERASURE_SERVICE: Fetcher /* cinaauth-privacy-erasure */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "RateLimitDurableObject";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string
		? EnvType[Binding]
		: string;
};
declare namespace NodeJS {
	interface ProcessEnv
		extends StringifyValues<
			Pick<
				Cloudflare.Env,
				| "CINAAUTH_URL"
				| "CINAAUTH_CUTOVER_STATE"
				| "CINAAUTH_SIWE_ENABLED"
				| "CINAAUTH_SIWE_ALLOWED_CHAIN_IDS"
				| "CINAAUTH_SIWE_RP_DOMAIN"
				| "CINAAUTH_SIWE_RP_URI"
				| "CINAAUTH_SIWE_ALLOW_LEGACY"
				| "CINAAUTH_SIWE_AUTO_SIGNUP"
			>
		> {}
}
