/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings ./src/worker-configuration.d.ts` (hash: ac252de44c30675dbe78d22397d9a00a)
interface __BaseEnv_CloudflareBindings {
	CINAAUTH_PRIVACY_EXPORTS: R2Bucket;
	LEGACY_D1: D1Database;
	HYPERDRIVE: Hyperdrive;
	CINAAUTH_DELIVERY_QUEUE: Queue;
	CINAAUTH_PRIVACY_EXPORT_QUEUE: Queue;
	CINAAUTH_DELIVERY_WEBHOOK_SECRET_STORE_V2: SecretsStoreSecret;
	CINAAUTH_ERASURE_WEBHOOK_SECRET_STORE_V2: SecretsStoreSecret;
	CINAADMIN_OIDC_CLIENT_SECRET_STORE_V2: SecretsStoreSecret;
	CINAADMIN_OIDC_BRIDGE_SECRET_STORE_V2: SecretsStoreSecret;
	VERSION_METADATA: WorkerVersionMetadata;
	CINAAUTH_URL: "https://auth.cinaseek.ai";
	CINAAUTH_CUTOVER_STATE: "live";
	RATE_LIMITER: DurableObjectNamespace<
		import("./index").RateLimitDurableObject
	>;
	CINAAUTH_DELIVERY_SERVICE: Fetcher /* cinaauth-delivery */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "RateLimitDurableObject";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string
		? EnvType[Binding]
		: string;
};
declare namespace NodeJS {
	interface ProcessEnv
		extends StringifyValues<
			Pick<Cloudflare.Env, "CINAAUTH_URL" | "CINAAUTH_CUTOVER_STATE">
		> {}
}
